[package]
name = "keybeat-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
clap-stdin = "0.5.1"
keybeat-core = { version = "0.1", path = "../keybeat-core/" }
cryptosystem = { version = "0.1", git = "https://github.com/arctic-hen7/cryptosystem" }
chrono = "0.4.39"
